import { createApp } from 'vue';
import { createPinia } from 'pinia';
import './style.css';
import 'element-plus/theme-chalk/index.css';
import './assets/iconfont/iconfont.js';
import App from './App.vue';
import router from './router';
import eventBus from 'vue3-eventbus';
createApp(App).use(router).use(createPinia()).use(eventBus).mount('#app');
// App;
